/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedConectarRouteImport } from './routes/_authenticated/conectar'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppIntegracaoRouteImport } from './routes/_authenticated/_app.integracao'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/_app.financeiro'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app.dashboard'
import { Route as AuthenticatedAppConversasRouteImport } from './routes/_authenticated/_app.conversas'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/_app.configuracoes'
import { Route as ApiPublicWebhookInstanceRouteImport } from './routes/api/public/webhook.$instance'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConectarRoute = AuthenticatedConectarRouteImport.update({
  id: '/conectar',
  path: '/conectar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIntegracaoRoute =
  AuthenticatedAppIntegracaoRouteImport.update({
    id: '/integracao',
    path: '/integracao',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConversasRoute =
  AuthenticatedAppConversasRouteImport.update({
    id: '/conversas',
    path: '/conversas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicWebhookInstanceRoute =
  ApiPublicWebhookInstanceRouteImport.update({
    id: '/api/public/webhook/$instance',
    path: '/api/public/webhook/$instance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conectar': typeof AuthenticatedConectarRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/conversas': typeof AuthenticatedAppConversasRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/integracao': typeof AuthenticatedAppIntegracaoRoute
  '/api/public/webhook/$instance': typeof ApiPublicWebhookInstanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conectar': typeof AuthenticatedConectarRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/conversas': typeof AuthenticatedAppConversasRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/integracao': typeof AuthenticatedAppIntegracaoRoute
  '/api/public/webhook/$instance': typeof ApiPublicWebhookInstanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/conectar': typeof AuthenticatedConectarRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/_app/conversas': typeof AuthenticatedAppConversasRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/_app/integracao': typeof AuthenticatedAppIntegracaoRoute
  '/api/public/webhook/$instance': typeof ApiPublicWebhookInstanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conectar'
    | '/onboarding'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/financeiro'
    | '/integracao'
    | '/api/public/webhook/$instance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conectar'
    | '/onboarding'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/financeiro'
    | '/integracao'
    | '/api/public/webhook/$instance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/_authenticated/conectar'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/configuracoes'
    | '/_authenticated/_app/conversas'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/financeiro'
    | '/_authenticated/_app/integracao'
    | '/api/public/webhook/$instance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhookInstanceRoute: typeof ApiPublicWebhookInstanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conectar': {
      id: '/_authenticated/conectar'
      path: '/conectar'
      fullPath: '/conectar'
      preLoaderRoute: typeof AuthenticatedConectarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/integracao': {
      id: '/_authenticated/_app/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof AuthenticatedAppIntegracaoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/financeiro': {
      id: '/_authenticated/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/conversas': {
      id: '/_authenticated/_app/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedAppConversasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/configuracoes': {
      id: '/_authenticated/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/webhook/$instance': {
      id: '/api/public/webhook/$instance'
      path: '/api/public/webhook/$instance'
      fullPath: '/api/public/webhook/$instance'
      preLoaderRoute: typeof ApiPublicWebhookInstanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppConversasRoute: typeof AuthenticatedAppConversasRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppIntegracaoRoute: typeof AuthenticatedAppIntegracaoRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppConversasRoute: AuthenticatedAppConversasRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppIntegracaoRoute: AuthenticatedAppIntegracaoRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedConectarRoute: typeof AuthenticatedConectarRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedConectarRoute: AuthenticatedConectarRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhookInstanceRoute: ApiPublicWebhookInstanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
